import os
import subprocess


def escape_latex(text: str) -> str:
    """
    LaTeX特殊文字を安全にエスケープ
    """

    if not text:
        return ""

    # 危険なLaTeXコマンド除去
    dangerous_commands = [
        "\\textbf",
        "\\begin",
        "\\end",
        "\\section",
        "\\subsection",
        "\\input",
        "\\include",
    ]

    for cmd in dangerous_commands:
        text = text.replace(cmd, "")

    # 特殊文字エスケープ
    replacements = {
        '&': r'\&',
        '%': r'\%',
        '$': r'\$',
        '#': r'\#',
        '_': r'\_',
        '{': r'\{',
        '}': r'\}',
        '~': r'\textasciitilde{}',
        '^': r'\textasciicircum{}',
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    return text


def markdown_to_latex(text: str) -> str:
    """
    MarkdownをLaTeXへ変換
    """

    lines = text.splitlines()

    converted = []

    for line in lines:

        # 見出し
        if line.startswith("# "):
            title = line[2:]
            converted.append(f"\\section*{{{title}}}")

        elif line.startswith("## "):
            title = line[3:]
            converted.append(f"\\subsection*{{{title}}}")

        elif line.startswith("### "):
            title = line[4:]
            converted.append(f"\\subsubsection*{{{title}}}")

        # 区切り線
        elif line.strip() == "---":
            converted.append("\\hrulefill")

        else:
            converted.append(line)

    return "\n".join(converted)


def generate_tex(
    note_text: str,
    output_tex="outputs/note.tex"
):
    """
    txt → tex
    """

    # LaTeX安全化
    note_text = escape_latex(note_text)

    # markdown風変換
    note_text = markdown_to_latex(note_text)

    tex_content = rf"""
\documentclass[12pt]{{article}}

\usepackage{{fontspec}}
\usepackage{{xeCJK}}

% 日本語フォント（Mac）
\setCJKmainfont{{Hiragino Mincho ProN}}
\setCJKsansfont{{Hiragino Sans}}

\usepackage{{amsmath}}
\usepackage{{amssymb}}
\usepackage{{geometry}}
\usepackage{{graphicx}}

\geometry{{a4paper, margin=25mm}}

\setlength{{\parindent}}{{0pt}}
\setlength{{\parskip}}{{0.8em}}

\title{{Lecture Note}}
\author{{Generated by AI}}
\date{{}}

\begin{{document}}

\maketitle

{note_text}

\end{{document}}
"""

    with open(output_tex, "w", encoding="utf-8") as f:
        f.write(tex_content)

    print(f"{output_tex} 生成完了")


def compile_pdf(
    tex_file="outputs/note.tex"
):
    """
    xelatexでPDF生成
    """

    print("===== PDFコンパイル開始 =====")

    tex_dir = os.path.dirname(tex_file)
    tex_name = os.path.basename(tex_file)

    cmd = [
        "xelatex",
        "-interaction=nonstopmode",
        tex_name
    ]

    try:

        subprocess.run(
            cmd,
            cwd=tex_dir,
            check=True,
            text=True
        )

        print("PDF生成完了")

    except subprocess.CalledProcessError as e:

        print("PDF生成失敗")
        print(e)


def create_pdf_from_text(
    input_txt="outputs/final_note.txt",
    output_tex="outputs/note.tex"
):
    """
    final_note.txt → note.tex → note.pdf
    """

    if not os.path.exists(input_txt):

        print(f"{input_txt} が存在しません")
        return

    with open(
        input_txt,
        "r",
        encoding="utf-8"
    ) as f:

        note_text = f.read()

    generate_tex(
        note_text,
        output_tex
    )

    compile_pdf(output_tex)


# main.py互換
def make_pdf():

    create_pdf_from_text()


if __name__ == "__main__":

    make_pdf()